workflows:
  release-workflow:
    name: Release Workflow (Android & iOS)
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK and AppBundle
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
          flutter build appbundle --release --android-skip-build-dependency-validation
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
